apiVersion: v1
kind: Service
metadata:
  name: service-product-review
  labels:
    app: product-review
    run: product-review
spec:
  ports:
    # the port that this service should serve on
  - name: http
    port: 8081
    targetPort: 8081
    nodePort: 30036
  selector:
    app: product-review
  type: NodePort